[package]
name = "protostar"
version = "0.4.0"
edition = "2021"

[dependencies]
cached = "0.43.0"
clap = { version = "4.1.3", features = ["derive"] }
color-eyre = "0.6.2"
directories = "5.0.0"
dirs = "5.0.0"
ez-pixmap = "0.2.2"
glam = { version = "0.24.0", features = ["mint"] }
image = "0.24.5"
lazy_static = "1.4.0"
linicon = "2.3.0"
manifest-dir-macros = "0.1.16"
mint = "0.5.9"
nix = "0.26.1"
regex = "1.7.1"
resvg = "0.29.0"
rustc-hash = "1.1.0"
serde = "1.0.155"
serde_json = "1.0.94"
serde_with = "2.3.1"
stardust-xr-fusion = "0.40.2"
stardust-xr-molecules = "0.24.3"
tokio = { version = "1.24.1", features = ["full"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tween = "2.0.0"
ustr = "0.9.0"
walkdir = "2.3.2"

[dev-dependencies]
tempdir = "0.3.7"

[patch.crates-io.stardust-xr-fusion]
path = "../../core/fusion"